FROM jenkins/jenkins:2.401.2-jdk17
USER root

#installer lsb-release utilitaire utilisé pour obtenir des informations sur la distribution 
#Linux en cours d'utilisation.
RUN apt-get update && apt-get install -y lsb-release

#installer maven
RUN apt-get update && apt-get install -y maven

#ajouter une clé de signature GPG au trousseau de clés de l'image Docker, utilisée pour vérifier
#l'authenticité et l'intégrité des paquets téléchargés depuis les référentiels Docker.
RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc \
  https://download.docker.com/linux/debian/gpg

#ajouter une nouvelle source de paquets APT, pour installer Docker à partir du référentiel officiel 
#de Docker pour les distributions Debian.
RUN echo "deb [arch=$(dpkg --print-architecture) \
  signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
  https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list

# installer le client Docker, Docker CLI
RUN apt-get update && apt-get install -y docker-ce-cli

USER jenkins

#installer des plugins 
RUN jenkins-plugin-cli --plugins "blueocean docker-workflow"
