version: '3.8'

services:

  docker-dind:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    networks:
      try:
        aliases:
          - docker  # Add the "docker" alias here
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins_docker_certs:/certs/client
      - jenkins_data:/var/jenkins_home
    ports:
      - "3000:3000"
      - "5000:5000"
      - "2376:2376"

  nexus:
    image: "sonatype/nexus3"
    volumes:
      - "./nexus/:/nexus-data"
    networks:
      - try
    ports:
      - "8081:8081"

  jenkins:
    image: myjenkins-blueocean:2.401.2-1
    container_name: jenkins-blueocean
    volumes:
      - jenkins_home:/var/jenkins_home
      - jenkins_docker_certs:/certs/client:ro
      - "./settings.xml:/var/jenkins_home/tools/hudson.tasks.Maven_MavenInstallation/Maven/conf/settings.xml"
    networks:
      - try
    ports:
      - "8083:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
    restart: on-failure


  sonarqube:
    image: sonarqube:7.6-community 
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      - try
    ports:
      - '9000:9000'
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar

  db:
    image: postgres
    networks:
      - try
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  tomcat:
    image: tomcat
    ports:
      - "8082:8080"
    volumes:
      - "./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml"
    networks:
      - try


networks:
  try:
    external: true

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
  jenkins_home:
  jenkins_docker_certs:
  jenkins_data:
